language: python
python:
    - 3.4
before_install:
    - sudo apt-get update
    - sudo apt-get install gfortran libopenblas-dev liblapack-dev
    - pip install tox
install: 
    - python3 setup.py install
script: 
    - python3 setup.py test
