language: python
python:
    - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq gfortran libopenblas-dev liblapack-dev
install: 
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
